const docsData = [
  // Web Standards
  { name: "MDN Web Docs", link: "https://developer.mozilla.org/", desc: "Official Mozilla documentation for HTML, CSS, JavaScript, Web APIs, and the modern web platform.", cat: "Web Standards" },
  { name: "WHATWG HTML Standard", link: "https://html.spec.whatwg.org/", desc: "Living standard for HTML maintained by WHATWG.", cat: "Web Standards" },
  { name: "W3C CSS Specifications", link: "https://www.w3.org/Style/CSS/specs.en.html", desc: "Official CSS specifications and modules from W3C.", cat: "Web Standards" },
  { name: "DOM Standard", link: "https://dom.spec.whatwg.org/", desc: "Official standard for the DOM platform and APIs.", cat: "Web Standards" },
  { name: "Fetch Standard", link: "https://fetch.spec.whatwg.org/", desc: "Official fetch standard for requests, responses, headers, and networking behavior.", cat: "Web Standards" },
  { name: "URL Standard", link: "https://url.spec.whatwg.org/", desc: "Official WHATWG URL parsing and handling standard.", cat: "Web Standards" },
  { name: "ECMAScript Specification", link: "https://tc39.es/ecma262/", desc: "Official ECMAScript language specification.", cat: "Web Standards" },
  { name: "WebAssembly Docs", link: "https://webassembly.org/docs/", desc: "Official WebAssembly documentation and core concepts.", cat: "Web Standards" },
  { name: "RFC Editor", link: "https://www.rfc-editor.org/", desc: "Canonical repository for RFC documents and Internet standards.", cat: "Web Standards" },
  { name: "IANA Protocol Registries", link: "https://www.iana.org/protocols", desc: "Official protocol and standards registries maintained by IANA.", cat: "Web Standards" },

  // Frontend
  { name: "React", link: "https://react.dev/", desc: "Official React documentation, guides, and API reference.", cat: "Frontend" },
  { name: "Vue.js", link: "https://vuejs.org/guide/introduction.html", desc: "Official Vue documentation and learning guide.", cat: "Frontend" },
  { name: "Angular", link: "https://angular.dev/", desc: "Official Angular documentation and framework guides.", cat: "Frontend" },
  { name: "Svelte", link: "https://svelte.dev/docs", desc: "Official Svelte docs, API, and examples.", cat: "Frontend" },
  { name: "Next.js", link: "https://nextjs.org/docs", desc: "Official Next.js documentation for React applications.", cat: "Frontend" },
  { name: "Nuxt", link: "https://nuxt.com/docs", desc: "Official Nuxt documentation for Vue-based full-stack apps.", cat: "Frontend" },
  { name: "Remix", link: "https://remix.run/docs", desc: "Official Remix framework documentation.", cat: "Frontend" },
  { name: "Astro", link: "https://docs.astro.build/", desc: "Official Astro documentation and project guides.", cat: "Frontend" },
  { name: "Tailwind CSS", link: "https://tailwindcss.com/docs", desc: "Official Tailwind CSS utility and configuration docs.", cat: "Frontend" },
  { name: "Bootstrap", link: "https://getbootstrap.com/docs/", desc: "Official Bootstrap documentation and components reference.", cat: "Frontend" },
  { name: "Vite", link: "https://vite.dev/guide/", desc: "Official Vite build tool documentation.", cat: "Frontend" },
  { name: "Webpack", link: "https://webpack.js.org/concepts/", desc: "Official webpack documentation for modules and bundling.", cat: "Frontend" },
  { name: "Parcel", link: "https://parceljs.org/docs/", desc: "Official Parcel bundler documentation.", cat: "Frontend" },
  { name: "TypeScript", link: "https://www.typescriptlang.org/docs/", desc: "Official TypeScript handbook and configuration reference.", cat: "Frontend" },

  // Backend
  { name: "Node.js", link: "https://nodejs.org/docs/latest/api/", desc: "Official Node.js API documentation.", cat: "Backend" },
  { name: "Deno", link: "https://docs.deno.com/", desc: "Official Deno runtime documentation.", cat: "Backend" },
  { name: "Bun", link: "https://bun.sh/docs", desc: "Official Bun runtime and tooling documentation.", cat: "Backend" },
  { name: "Express", link: "https://expressjs.com/", desc: "Official Express web framework documentation.", cat: "Backend" },
  { name: "Fastify", link: "https://fastify.dev/docs/latest/", desc: "Official Fastify framework docs for high-performance Node.js APIs.", cat: "Backend" },
  { name: "NestJS", link: "https://docs.nestjs.com/", desc: "Official NestJS documentation for scalable backend apps.", cat: "Backend" },
  { name: "Python Docs", link: "https://docs.python.org/3/", desc: "Official Python language and standard library documentation.", cat: "Backend" },
  { name: "Django", link: "https://docs.djangoproject.com/", desc: "Official Django documentation and reference.", cat: "Backend" },
  { name: "Flask", link: "https://flask.palletsprojects.com/", desc: "Official Flask documentation for Python web development.", cat: "Backend" },
  { name: "FastAPI", link: "https://fastapi.tiangolo.com/", desc: "Official FastAPI docs for modern Python APIs.", cat: "Backend" },
  { name: "Ruby on Rails", link: "https://guides.rubyonrails.org/", desc: "Official Rails guides and application framework documentation.", cat: "Backend" },
  { name: "Laravel", link: "https://laravel.com/docs", desc: "Official Laravel PHP framework documentation.", cat: "Backend" },
  { name: "PHP Manual", link: "https://www.php.net/docs.php", desc: "Official PHP manual and language reference.", cat: "Backend" },
  { name: "Spring Framework", link: "https://docs.spring.io/spring-framework/reference/", desc: "Official Spring Framework reference documentation.", cat: "Backend" },
  { name: "ASP.NET Core", link: "https://learn.microsoft.com/aspnet/core/", desc: "Official Microsoft ASP.NET Core docs.", cat: "Backend" },
  { name: "Go Docs", link: "https://go.dev/doc/", desc: "Official Go language documentation and references.", cat: "Backend" },
  { name: "Rust", link: "https://www.rust-lang.org/learn", desc: "Official Rust language portal and learning docs.", cat: "Backend" },
  { name: "Rust Standard Library", link: "https://doc.rust-lang.org/std/", desc: "Official Rust standard library reference.", cat: "Backend" },

  // Databases
  { name: "PostgreSQL", link: "https://www.postgresql.org/docs/", desc: "Official PostgreSQL documentation.", cat: "Databases" },
  { name: "MySQL", link: "https://dev.mysql.com/doc/", desc: "Official MySQL documentation portal.", cat: "Databases" },
  { name: "MariaDB", link: "https://mariadb.com/kb/en/documentation/", desc: "Official MariaDB documentation knowledge base.", cat: "Databases" },
  { name: "SQLite", link: "https://www.sqlite.org/docs.html", desc: "Official SQLite documentation and technical references.", cat: "Databases" },
  { name: "MongoDB", link: "https://www.mongodb.com/docs/", desc: "Official MongoDB documentation for database, Atlas, and drivers.", cat: "Databases" },
  { name: "Redis", link: "https://redis.io/docs/latest/", desc: "Official Redis documentation and command references.", cat: "Databases" },
  { name: "Elasticsearch", link: "https://www.elastic.co/guide/index.html", desc: "Official Elastic documentation hub for Elasticsearch and related products.", cat: "Databases" },
  { name: "OpenSearch", link: "https://docs.opensearch.org/", desc: "Official OpenSearch documentation.", cat: "Databases" },
  { name: "Neo4j", link: "https://neo4j.com/docs/", desc: "Official Neo4j graph database documentation.", cat: "Databases" },
  { name: "Apache Cassandra", link: "https://cassandra.apache.org/doc/latest/", desc: "Official Apache Cassandra documentation.", cat: "Databases" },
  { name: "InfluxDB", link: "https://docs.influxdata.com/influxdb/", desc: "Official InfluxDB documentation for time series workloads.", cat: "Databases" },
  { name: "DuckDB", link: "https://duckdb.org/docs/", desc: "Official DuckDB documentation.", cat: "Databases" },

  // Cloud
  { name: "AWS Documentation", link: "https://docs.aws.amazon.com/", desc: "Official Amazon Web Services documentation hub.", cat: "Cloud" },
  { name: "Amazon EC2", link: "https://docs.aws.amazon.com/ec2/", desc: "Official documentation for Amazon EC2.", cat: "Cloud" },
  { name: "Amazon S3", link: "https://docs.aws.amazon.com/s3/", desc: "Official documentation for Amazon S3.", cat: "Cloud" },
  { name: "Amazon Lambda", link: "https://docs.aws.amazon.com/lambda/", desc: "Official documentation for AWS Lambda.", cat: "Cloud" },
  { name: "Microsoft Learn", link: "https://learn.microsoft.com/", desc: "Official Microsoft documentation portal.", cat: "Cloud" },
  { name: "Azure Documentation", link: "https://learn.microsoft.com/azure/", desc: "Official Microsoft Azure documentation.", cat: "Cloud" },
  { name: "Azure Functions", link: "https://learn.microsoft.com/azure/azure-functions/", desc: "Official docs for Azure Functions.", cat: "Cloud" },
  { name: "Google Cloud Documentation", link: "https://cloud.google.com/docs", desc: "Official Google Cloud documentation hub.", cat: "Cloud" },
  { name: "Cloud Run", link: "https://cloud.google.com/run/docs", desc: "Official docs for Google Cloud Run.", cat: "Cloud" },
  { name: "Firebase", link: "https://firebase.google.com/docs", desc: "Official Firebase documentation.", cat: "Cloud" },
  { name: "Cloudflare Docs", link: "https://developers.cloudflare.com/", desc: "Official Cloudflare documentation for edge, DNS, workers, and security.", cat: "Cloud" },
  { name: "Cloudflare Workers", link: "https://developers.cloudflare.com/workers/", desc: "Official documentation for Cloudflare Workers.", cat: "Cloud" },
  { name: "DigitalOcean Docs", link: "https://docs.digitalocean.com/", desc: "Official DigitalOcean product documentation.", cat: "Cloud" },
  { name: "Vercel Docs", link: "https://vercel.com/docs", desc: "Official Vercel documentation.", cat: "Cloud" },
  { name: "Netlify Docs", link: "https://docs.netlify.com/", desc: "Official Netlify documentation.", cat: "Cloud" },

  // DevOps
  { name: "Docker Docs", link: "https://docs.docker.com/", desc: "Official Docker documentation for images, containers, Compose, and more.", cat: "DevOps" },
  { name: "Docker Compose", link: "https://docs.docker.com/compose/", desc: "Official documentation for Docker Compose.", cat: "DevOps" },
  { name: "Kubernetes", link: "https://kubernetes.io/docs/", desc: "Official Kubernetes documentation.", cat: "DevOps" },
  { name: "Helm", link: "https://helm.sh/docs/", desc: "Official Helm documentation for Kubernetes package management.", cat: "DevOps" },
  { name: "Terraform", link: "https://developer.hashicorp.com/terraform/docs", desc: "Official Terraform documentation.", cat: "DevOps" },
  { name: "Packer", link: "https://developer.hashicorp.com/packer/docs", desc: "Official Packer documentation.", cat: "DevOps" },
  { name: "Ansible", link: "https://docs.ansible.com/", desc: "Official Ansible documentation.", cat: "DevOps" },
  { name: "Jenkins", link: "https://www.jenkins.io/doc/", desc: "Official Jenkins documentation.", cat: "DevOps" },
  { name: "GitHub Docs", link: "https://docs.github.com/", desc: "Official GitHub documentation for repos, Actions, packages, and more.", cat: "DevOps" },
  { name: "GitHub Actions", link: "https://docs.github.com/actions", desc: "Official documentation for GitHub Actions.", cat: "DevOps" },
  { name: "GitLab Docs", link: "https://docs.gitlab.com/", desc: "Official GitLab documentation.", cat: "DevOps" },
  { name: "Prometheus", link: "https://prometheus.io/docs/", desc: "Official Prometheus documentation.", cat: "DevOps" },
  { name: "Grafana", link: "https://grafana.com/docs/", desc: "Official Grafana documentation.", cat: "DevOps" },
  { name: "NGINX", link: "https://nginx.org/en/docs/", desc: "Official NGINX documentation.", cat: "DevOps" },
  { name: "Apache HTTP Server", link: "https://httpd.apache.org/docs/", desc: "Official Apache HTTP Server documentation.", cat: "DevOps" },

  // Security
  { name: "OWASP", link: "https://owasp.org/", desc: "Official OWASP project portal for secure software references.", cat: "Security" },
  { name: "OWASP Top 10", link: "https://owasp.org/www-project-top-ten/", desc: "Official OWASP Top 10 project page.", cat: "Security" },
  { name: "NIST CSRC", link: "https://csrc.nist.gov/", desc: "Official NIST Computer Security Resource Center.", cat: "Security" },
  { name: "NIST Cybersecurity Framework", link: "https://www.nist.gov/cyberframework", desc: "Official NIST Cybersecurity Framework portal.", cat: "Security" },
  { name: "CISA", link: "https://www.cisa.gov/", desc: "Official U.S. Cybersecurity and Infrastructure Security Agency site.", cat: "Security" },
  { name: "MITRE ATT&CK", link: "https://attack.mitre.org/", desc: "Official MITRE ATT&CK knowledge base.", cat: "Security" },
  { name: "CWE", link: "https://cwe.mitre.org/", desc: "Official Common Weakness Enumeration project.", cat: "Security" },
  { name: "CVE Program", link: "https://www.cve.org/", desc: "Official CVE program portal.", cat: "Security" },
  { name: "OpenSSF", link: "https://openssf.org/", desc: "Official Open Source Security Foundation site.", cat: "Security" },
  { name: "Sigstore Docs", link: "https://docs.sigstore.dev/", desc: "Official Sigstore documentation for signing and provenance.", cat: "Security" },
  { name: "OpenID Connect Specs", link: "https://openid.net/developers/specs/", desc: "Official OpenID Connect specifications.", cat: "Security" },
  { name: "OAuth 2.0", link: "https://oauth.net/2/", desc: "Official OAuth 2.0 developer documentation.", cat: "Security" },

  // AI
  { name: "OpenAI Research", link: "https://openai.com/research", desc: "Official OpenAI research publications.", cat: "AI" },
  { name: "OpenAI Platform Docs", link: "https://platform.openai.com/docs", desc: "Official OpenAI developer platform documentation.", cat: "AI" },
  { name: "Hugging Face Docs", link: "https://huggingface.co/docs", desc: "Official Hugging Face documentation.", cat: "AI" },
  { name: "PyTorch", link: "https://pytorch.org/docs/stable/index.html", desc: "Official PyTorch documentation.", cat: "AI" },
  { name: "TensorFlow", link: "https://www.tensorflow.org/guide", desc: "Official TensorFlow guides and references.", cat: "AI" },
  { name: "Keras", link: "https://keras.io/api/", desc: "Official Keras API documentation.", cat: "AI" },
  { name: "scikit-learn", link: "https://scikit-learn.org/stable/documentation.html", desc: "Official scikit-learn documentation.", cat: "AI" },
  { name: "JAX", link: "https://docs.jax.dev/", desc: "Official JAX documentation.", cat: "AI" },
  { name: "ONNX", link: "https://onnx.ai/", desc: "Official ONNX docs and ecosystem references.", cat: "AI" },
  { name: "MLflow", link: "https://mlflow.org/docs/latest/index.html", desc: "Official MLflow documentation.", cat: "AI" },

  // Mobile
  { name: "Android Developers", link: "https://developer.android.com/docs", desc: "Official Android developer documentation.", cat: "Mobile" },
  { name: "Kotlin Docs", link: "https://kotlinlang.org/docs/home.html", desc: "Official Kotlin language documentation.", cat: "Mobile" },
  { name: "Jetpack Compose", link: "https://developer.android.com/jetpack/compose/documentation", desc: "Official Jetpack Compose documentation.", cat: "Mobile" },
  { name: "Apple Developer Documentation", link: "https://developer.apple.com/documentation/", desc: "Official Apple developer documentation for iOS, macOS, and frameworks.", cat: "Mobile" },
  { name: "Swift", link: "https://www.swift.org/documentation/", desc: "Official Swift language documentation.", cat: "Mobile" },
  { name: "SwiftUI", link: "https://developer.apple.com/documentation/swiftui/", desc: "Official SwiftUI documentation from Apple.", cat: "Mobile" },
  { name: "React Native", link: "https://reactnative.dev/docs/getting-started", desc: "Official React Native documentation.", cat: "Mobile" },
  { name: "Expo", link: "https://docs.expo.dev/", desc: "Official Expo documentation.", cat: "Mobile" },
  { name: "Flutter", link: "https://docs.flutter.dev/", desc: "Official Flutter documentation.", cat: "Mobile" },
  { name: "Dart", link: "https://dart.dev/guides", desc: "Official Dart language documentation.", cat: "Mobile" },

  // Systems
  { name: "Linux Kernel Docs", link: "https://docs.kernel.org/", desc: "Official Linux kernel documentation.", cat: "Systems" },
  { name: "Arch Wiki", link: "https://wiki.archlinux.org/", desc: "Canonical Arch Linux wiki used as a primary Linux reference.", cat: "Systems" },
  { name: "systemd", link: "https://www.freedesktop.org/software/systemd/man/latest/", desc: "Official systemd manual pages and references.", cat: "Systems" },
  { name: "GNU Bash Manual", link: "https://www.gnu.org/software/bash/manual/", desc: "Official GNU Bash manual.", cat: "Systems" },
  { name: "GNU Coreutils", link: "https://www.gnu.org/software/coreutils/manual/", desc: "Official GNU Coreutils manual.", cat: "Systems" },
  { name: "OpenSSH", link: "https://www.openssh.com/manual.html", desc: "Official OpenSSH manual pages and docs.", cat: "Systems" },
  { name: "Podman", link: "https://docs.podman.io/", desc: "Official Podman documentation.", cat: "Systems" },
  { name: "QEMU", link: "https://www.qemu.org/docs/master/", desc: "Official QEMU documentation.", cat: "Systems" },
  { name: "VirtualBox", link: "https://www.virtualbox.org/manual/", desc: "Official VirtualBox user manual.", cat: "Systems" },
  { name: "Wayland", link: "https://wayland.freedesktop.org/docs/html/", desc: "Official Wayland protocol documentation.", cat: "Systems" },

  // APIs
  { name: "OpenAPI Specification", link: "https://swagger.io/specification/", desc: "Official OpenAPI specification documentation.", cat: "APIs" },
  { name: "GraphQL", link: "https://graphql.org/learn/", desc: "Official GraphQL learning portal and references.", cat: "APIs" },
  { name: "gRPC", link: "https://grpc.io/docs/", desc: "Official gRPC documentation.", cat: "APIs" },
  { name: "Protocol Buffers", link: "https://protobuf.dev/", desc: "Official Protocol Buffers documentation.", cat: "APIs" },
  { name: "JSON Schema", link: "https://json-schema.org/learn", desc: "Official JSON Schema learning resources.", cat: "APIs" },
  { name: "AsyncAPI", link: "https://www.asyncapi.com/docs", desc: "Official AsyncAPI documentation.", cat: "APIs" },
  { name: "Apache Kafka", link: "https://kafka.apache.org/documentation/", desc: "Official Apache Kafka documentation.", cat: "APIs" },
  { name: "RabbitMQ", link: "https://www.rabbitmq.com/docs", desc: "Official RabbitMQ documentation.", cat: "APIs" },
  { name: "Apache Pulsar", link: "https://pulsar.apache.org/docs/", desc: "Official Apache Pulsar documentation.", cat: "APIs" },
  { name: "Socket.IO", link: "https://socket.io/docs/v4/", desc: "Official Socket.IO documentation.", cat: "APIs" },

  // Testing
  { name: "Playwright", link: "https://playwright.dev/docs/intro", desc: "Official Playwright documentation for browser automation and testing.", cat: "Testing" },
  { name: "Cypress", link: "https://docs.cypress.io/", desc: "Official Cypress documentation.", cat: "Testing" },
  { name: "Jest", link: "https://jestjs.io/docs/getting-started", desc: "Official Jest documentation.", cat: "Testing" },
  { name: "Vitest", link: "https://vitest.dev/guide/", desc: "Official Vitest documentation.", cat: "Testing" },
  { name: "Pytest", link: "https://docs.pytest.org/", desc: "Official pytest documentation.", cat: "Testing" },
  { name: "JUnit 5", link: "https://junit.org/junit5/docs/current/user-guide/", desc: "Official JUnit 5 user guide.", cat: "Testing" },
  { name: "Selenium", link: "https://www.selenium.dev/documentation/", desc: "Official Selenium documentation.", cat: "Testing" },
  { name: "Postman Learning Center", link: "https://learning.postman.com/", desc: "Official Postman documentation and learning center.", cat: "Testing" },

  // Design
  { name: "Figma Help Center", link: "https://help.figma.com/", desc: "Official Figma documentation and help center.", cat: "Design" },
  { name: "Material Design", link: "https://m3.material.io/", desc: "Official Material Design guidelines and component documentation.", cat: "Design" },
  { name: "Atlassian Design System", link: "https://atlassian.design/", desc: "Official Atlassian Design System documentation.", cat: "Design" },
  { name: "Carbon Design System", link: "https://carbondesignsystem.com/", desc: "Official IBM Carbon Design System documentation.", cat: "Design" },
  { name: "USWDS", link: "https://designsystem.digital.gov/", desc: "Official U.S. Web Design System documentation.", cat: "Design" },
  { name: "WCAG Overview", link: "https://www.w3.org/WAI/standards-guidelines/wcag/", desc: "Official W3C WCAG accessibility guidelines overview.", cat: "Design" },
  { name: "WAI-ARIA", link: "https://www.w3.org/WAI/standards-guidelines/aria/", desc: "Official WAI-ARIA accessibility standards documentation.", cat: "Design" },
  { name: "A11Y Project", link: "https://www.a11yproject.com/", desc: "Well-known accessibility resource used by frontend developers.", cat: "Design" }
]
window.DOCS_DATA = docsData;

